import type { AuditRun } from '../types/index.js';
import { env } from '../config/env.js';

export async function generatePdf(audit: AuditRun): Promise<Buffer> {
  const html = buildReportHtml(audit);

  try {
    const { default: puppeteer } = await import('puppeteer');
    const launchOptions: Parameters<typeof puppeteer.launch>[0] = {
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    };
    if (process.env.PUPPETEER_EXECUTABLE_PATH) {
      launchOptions.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH;
    }
    const browser = await puppeteer.launch(launchOptions);
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'domcontentloaded' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
    });
    await browser.close();
    return Buffer.from(pdf);
  } catch {
    return Buffer.from(html, 'utf-8');
  }
}

function buildReportHtml(audit: AuditRun): string {
  const totalImpact = audit.findings.reduce((s, f) => s + f.impactMonthly, 0);
  const healthScore = audit.healthScores.length
    ? Math.round(audit.healthScores.reduce((s, h) => s + h.score, 0) / audit.healthScores.length)
    : 38;

  const findingsHtml = audit.findings
    .slice(0, 20)
    .map(
      (f) => `
    <div style="border:1px solid #1E2D48;border-radius:8px;padding:16px;margin-bottom:12px;background:#141C2E;">
      <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
        <span style="color:${severityColor(f.severity)};font-weight:600;font-size:12px;">${f.severity}</span>
        <span style="color:#00C9A7;font-weight:700;">$${f.impactMonthly.toLocaleString()}/mo</span>
      </div>
      <h3 style="color:#fff;margin:0 0 8px;font-size:14px;">${f.title}</h3>
      <p style="color:#C0CCDB;font-size:12px;margin:0;">${f.description}</p>
    </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Segoe UI', Roboto, sans-serif; background: #07090F; color: #C0CCDB; margin: 0; padding: 40px; }
    h1 { color: #fff; }
    .accent { color: #FF6B2B; }
    .teal { color: #00C9A7; }
    .metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }
    .metric { background: #141C2E; border: 1px solid #1E2D48; border-radius: 8px; padding: 16px; text-align: center; }
    .metric-value { font-size: 28px; font-weight: 700; }
  </style>
</head>
<body>
  <h1>AdAudit Pro — <span class="accent">${audit.accountName}</span></h1>
  <p>Generated ${new Date().toLocaleDateString()} • ${audit.dataWindowDays}-day data window • Engine v${audit.engineVersion}</p>

  <div class="metrics">
    <div class="metric"><div class="metric-value" style="color:#FF6B2B;">${audit.findings.length}</div><div>Findings</div></div>
    <div class="metric"><div class="metric-value teal">$${totalImpact.toLocaleString()}</div><div>Monthly Impact</div></div>
    <div class="metric"><div class="metric-value teal">$${(totalImpact * 12).toLocaleString()}</div><div>Annual Opportunity</div></div>
    <div class="metric"><div class="metric-value" style="color:#FF6B2B;">${healthScore}/100</div><div>Health Score</div></div>
  </div>

  <h2 style="color:#fff;">Executive Summary</h2>
  <p>${audit.executiveSummary || 'Audit complete. Review findings below.'}</p>

  <h2 style="color:#fff;">Top Findings</h2>
  ${findingsHtml}

  <p style="margin-top:40px;font-size:11px;color:#6B7D96;">Generated by AdAudit Pro • ${env.clientUrl}</p>
</body>
</html>`;
}

function severityColor(severity: string): string {
  const map: Record<string, string> = {
    CRITICAL: '#FF4444',
    HIGH: '#FF6B2B',
    MEDIUM: '#F8A51B',
    LOW: '#00C9A7',
  };
  return map[severity] || '#C0CCDB';
}
